version: '3.8'

services:
    paintress-server:
        build:
            context: .
            dockerfile: ./apps/paintress-server/dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - PORT=3000
        restart: unless-stopped
