import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api/v1"; // generated by openapi-typescript
import { authStore } from "./store/auth.store";

const BASE_URL = process.env.VITE_PUBLIC_API_URL || "http://localhost:8000";

let access_token = "";

const isTokenValid = (token: string) => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [_, payload] = `${token}`.split(".");

  const decoded = JSON.parse(atob(payload));

  const now = Date.now() / 1000;

  return decoded.exp > now - 10;
};

const getAccessToken = async () => {
  if (access_token && isTokenValid(access_token)) {
    return access_token;
  }

  const token = authStore.getState().token;

  if (!token) {
    return "";
  }

  const response = await fetch(`${BASE_URL}/api/v1/auth/refresh`, {
    method: "POST",
    body: JSON.stringify({ refresh_token: token }),
  });

  const data = await response.json();

  console.log(data);

  access_token = data.access_token;

  return access_token;
};

const fetchClient = createFetchClient<paths>({
  baseUrl: BASE_URL,
});

fetchClient.use({
  onRequest: async (option) => {
    const token = authStore.getState().token;

    if (token) {
      option.request.headers.set(
        "Authorization",
        `Bearer ${await getAccessToken()}`
      );
    }
    
    return option.request;
  },
});

export const $api = createClient(fetchClient);
