"""Add clerk_id to users table

Revision ID: 7b9ef4f516ae
Revises: 92f57854037d
Create Date: 2025-07-31 22:11:06.042943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7b9ef4f516ae"
down_revision: Union[str, Sequence[str], None] = "92f57854037d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("clerk_id", sa.String(), nullable=True, unique=True),
    )
    op.create_unique_constraint("clerk_id", "users", ["clerk_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "clerk_id")
    # ### end Alembic commands ###
